game/src/main/org/apollo/game/model/Position.java
game/src/test/org/apollo/game/model/TestPosition.java

Fixes the check in the Position constructor, also includes a simple test.

Fixes issue #70

---

game/src/main/org/apollo/game/model/World.java
game/src/main/org/apollo/game/model/entity/Player.java
game/src/main/org/apollo/game/service/GameService.java
game/src/main/org/apollo/game/session/GameSession.java
game/src/main/org/apollo/game/session/LoginSession.java

Let me know if anything needs to be changed :)

New players will be queued rather than added right away.

---

data/plugins/cmd/punishment/plugin.xml
data/plugins/cmd/punishment/punish.rb
game/src/main/org/apollo/game/io/player/BinaryPlayerSerializer.java
game/src/main/org/apollo/game/message/handler/ChatMessageHandler.java
game/src/main/org/apollo/game/model/entity/Player.java

Ban and mute support, commands included.

---

data/plugins/combat/wilderness.rb

When you entered the wilderness it would start at level 0

 Fixed Wilderness level 0

---

data/plugins/skill/magic/teleport.rb

Was never adding xp for teleporting

Fixed Adding xp to teleporting

---

game/src/main/org/apollo/game/service/GameService.java

It use to always finalize the player even if it failed with a status

Fixed Player Already Online

---

data/plugins/player-action/action.rb

Fixed the issue https://github.com/apollo-rsps/apollo/issues/113
when you left the wilderness

Fixed the issue #113

---

game/src/main/org/apollo/game/model/entity/MobRepository.java
game/src/test/org/apollo/game/model/entity/MobRepositoryTest.java

This PR also has the fixes @Major- requested

Fixes issue #98 (also adds unit test for MobRepository)

---

game/src/main/org/apollo/game/model/entity/Player.java
game/src/main/org/apollo/game/model/inv/AppearanceInventoryListener.java
game/src/main/org/apollo/game/model/skill/SynchronizationSkillListener.java
game/src/main/org/apollo/game/sync/task/PlayerSynchronizationTask.java

Fixes issue #84 (Appearance caching)

---

data/plugins/cmd/npc/spawn.rb

fixes issue #143 - ::mass broken

---

data/plugins/skill/magic/alchemy.rb

* Low and high alch have there own delay now when they use to share the same.
* Runes are checked for the main rune before the elemental which its how its done in runescape.
* Only item that is not allowed to be alched is coins I checked tokkul as well and its allowed.
* Fixed gold amount received it was way off.

Fixed small issues with alchemy

---

cache/src/main/org/apollo/cache/def/ItemDefinition.java

* Made the noted item value use the value from the unoted item

Fixed Noted Item Value

---

data/plugins/consumables/consumable.rb

* Removed the equal check due to causing issue's with food delays since when you eat one food it should be on the same tick

Fixed food eating delays

---

data/plugins/consumables/consumable.rb
data/plugins/consumables/food.rb
data/plugins/consumables/potions.rb

fixes issue #148 - add consumable delays

---

game/src/main/org/apollo/game/model/area/Region.java
game/src/main/org/apollo/game/service/GameService.java

This closes #155, closes #154 and closes #107

Resolves issue #155, resolves issue #154, resolves issue #107

---

data/plugins/consumables/consumable.rb
data/plugins/consumables/food.rb
data/plugins/consumables/potions.rb

fixes the bug where you cannot eat and drink a potion at the same time.

separate potion and food consume delays

---

data/plugins/consumables/food.rb

Squashed @WizardJesse1 commits for this as he was having difficulty.

Fixed "It heals some health" food consumable message.

---

game/src/main/org/apollo/game/model/World.java
game/src/main/org/apollo/game/model/area/Region.java
game/src/main/org/apollo/game/model/entity/MobRepository.java
game/src/test/org/apollo/game/model/entity/MobRepositoryTest.java

Fixes issue #142

---

game/src/main/org/apollo/game/sync/task/NpcSynchronizationTask.java
game/src/main/org/apollo/game/sync/task/PlayerSynchronizationTask.java

Changed synchronization implementation to iterate over surrounding regions for nearby mobs

---

data/plugins/player-action/action.rb

The order for player options were wrong. It's all in the correct order now

Fixed Player Option Order

---

data/plugins/areas/areas.rb

Notify area listeners upon login

---

data/plugins/areas/actions.rb
data/plugins/areas/areas.rb
data/plugins/combat/wilderness.rb

Let area listeners have access to the updated position from the MobPositionUpdateEvent

---

game/src/main/org/apollo/game/model/entity/attr/AttributeDefinition.java
game/src/main/org/apollo/game/model/entity/attr/AttributeMap.java
game/src/main/org/apollo/game/model/entity/attr/StringAttribute.java
game/src/test/org/apollo/game/model/entity/attr/AttributeTests.java

Fix String attribute encoding delimiter

---

game/src/main/org/apollo/game/GameConstants.java
game/src/main/org/apollo/game/model/World.java

Queue npcs before unregistering, increase maximum messages

---

data/plugins/skill/magic/enchant.rb

Currently uses the correct animation now

Fix enchant ring animation

---

data/plugins/skill/herblore/herb.rb

It has the correct message now and it supports a/an

Fixed Issue #186

---

data/plugins/skill/magic/magic.rb

I forgot to check a few things when i changed magic check's
Issues Fix
* You couldn't teleport but now you can
* Illegal items would throw an error
* Process elements would get removed even if you couldn't cast the spell due to moving illegal items

Fix Magic Check Issues

---

game/src/main/org/apollo/game/model/entity/path/AStarPathfindingAlgorithm.java
game/src/main/org/apollo/game/model/entity/path/EuclideanHeuristic.java

Didn't bother to look too much into the implementation for this old fix. It uses euclidean distance which seemingly generates much better paths than the chebyshev heuristic. 
This also addresses the problem in issue #106.

Fix the A* path finding implementation

---

data/plugins/location/al-kharid/npcs.rb

* Added every npc that was missing from al-kharid
* Removed and moved any npcs that were not in the correct area

More Npcs to Al-Kharid

---

data/plugins/location/edgeville/npcs.rb

* Added every npc that was missing from edgeville 
* Removed and moved any npcs that were not in the correct area

Added Edgeville Npcs

---

data/plugins/location/varrock/npcs.rb
data/plugins/location/varrock/plugin.xml

* Fixed The big indent so it should be readable now

Added Varrock Npcs

---

data/plugins/location/falador/npcs.rb
data/plugins/location/falador/plugin.xml

* Added most of the npcs to falador

Npcs added to Falador

---

data/plugins/bootstrap.rb
data/plugins/dialogue/dialogue.rb
data/plugins/location/tutorial-island/guide.rb
data/plugins/location/tutorial-island/instructions.rb
data/plugins/location/tutorial-island/plugin.xml
data/plugins/location/tutorial-island/stages.rb
data/plugins/location/tutorial-island/survival.rb
data/plugins/navigation/door/door.rb
game/src/main/org/apollo/game/message/impl/HintIconMessage.java
game/src/main/org/apollo/game/message/impl/PositionHintIconMessage.java
game/src/main/org/apollo/game/model/World.java
game/src/main/org/apollo/game/model/event/ProxyEvent.java
game/src/main/org/apollo/game/model/event/ProxyEventListener.java
game/src/main/org/apollo/game/plugin/RubyPluginEnvironment.java
game/src/main/org/apollo/game/release/r377/FlashTabInterfaceMessageEncoder.java

cc @garyttierney @ryleykimmel needs CR

Fix many issues with the Tutorial island plugin

---

data/plugins/location/falador/npcs.rb
data/plugins/location/varrock/npcs.rb
data/plugins/location/varrock/shops.rb
data/plugins/shops/shops.rb

I think this is a pretty good change

Create shops using npc and item names instead of ids.

---

game/src/main/org/apollo/game/release/r317/PlayerSynchronizationMessageEncoder.java
game/src/main/org/apollo/game/release/r377/PlayerSynchronizationMessageEncoder.java

* Beards are now fixed for items like coifs, dharok helms, dragon med

Fixed beards for helmets.

---

pom.xml

Hello,
I updated the POM with the latest versions of plugins.

POM : new plugin version

---

data/plugins/skill/fishing/fishing.rb
game/src/main/org/apollo/game/model/inv/Inventory.java
game/src/main/org/apollo/game/model/inv/transaction/ItemTransaction.java
game/src/main/org/apollo/game/model/inv/transaction/SlottedTransactionItem.java
game/src/main/org/apollo/game/model/inv/transaction/StackedTransactionItem.java
game/src/main/org/apollo/game/model/inv/transaction/TransactionBlock.java
game/src/main/org/apollo/game/model/inv/transaction/TransactionBuilder.java
game/src/main/org/apollo/game/model/inv/transaction/TransactionFailureListener.java
game/src/main/org/apollo/game/model/inv/transaction/TransactionItem.java
game/src/main/org/apollo/game/model/inv/transaction/TransactionListener.java

- Document transaction classes

New remove method in Inventory

---

cache/src/main/org/apollo/cache/IndexedFileSystem.java

Hello,
We found a way to simplify the method getCrcs so we did it.
Thanks

Simplify the getter of Crcs

---

data/plugins/dialogue/dialogue.rb

Hello,
I refactored the wrap method in dialogue.rb. I think it's easier to read and test the code. I also corrected some bug.
Thank.

refactor wrap in dialogue.rb

---

game/src/main/org/apollo/game/fs/decoder/GameObjectDecoder.java

new PR after bad rebase

---

data/plugins/consumables/consumable.rb
data/plugins/consumables/drink.rb
data/plugins/consumables/food.rb

Hello, 
We saw a TODO with @KGALLET, so we create a new ruby class named "drink.rb". 
We separate drinks and foods between those two classes to differentiate the two types of consumable.
We are not sure about the drink sound id as we can't test the sound.
Thanks.

creation of drink.rb

---

game/src/test/org/apollo/game/model/entity/SkillSetTests.java

Hello,
I created some tests for a few methods of Skillset.java. The only methods that aren't tested are really simple so they didn't need any tests.

Adding tests to Skillset.java

---

game/src/main/org/apollo/game/model/inv/Inventory.java

Hello,
In Inventory.java, I extracted the case when the item is stackable and created a method for a better visibility in the method add.

Refactor method add in Inventory.java

---

data/plugins/location/tutorial-island/survival.rb

Hello,
I saw a typo in survival.rb and corrected it.
Thanks

Change conversation name in survival.rb

---

data/plugins/location/tutorial-island/instructions.rb

Hello,
I added the text in instruction following the exact text of Runescape's original tutorial island.
Are you interested if I continue to add the following dialogue in the future ?
Thanks.

Add text in instruction.rb

---

game/src/main/org/apollo/game/message/handler/EquipItemHandler.java

Hello,
We refactored the method handle in EquipItemHandler.java for better visibility.
To do that we extracted the case when the equipment is defined as two handed and created a method handleTwoHanded for that.
Thanks

refactor method handle in EquipItemHandler.java

---

data/plugins/location/tutorial-island/instructions.rb
data/plugins/location/tutorial-island/survival.rb

Hello, 
We fixed the issue #178.
Thanks.

Fix issue #178

---

game/src/main/org/apollo/game/action/DistancedAction.java

Before:
http://recordit.co/qFCM2jaox2
After:
http://recordit.co/Jre4B5s1zT

Fix Distance check

---

cache/src/main/org/apollo/cache/IndexedFileSystem.java
game/src/main/org/apollo/game/fs/decoder/WorldMapDecoder.java
game/src/main/org/apollo/game/model/World.java
game/src/main/org/apollo/game/model/area/Region.java
game/src/main/org/apollo/game/model/area/collision/CollisionManager.java
game/src/main/org/apollo/game/model/area/collision/CollisionUpdate.java
game/src/main/org/apollo/game/model/area/collision/CollisionUpdateListener.java
game/src/main/org/apollo/game/model/area/collision/CollisionUpdateType.java
game/src/main/org/apollo/game/model/entity/EntityType.java

Also adds a couple of static imports for nicety

Condense some unnecessarily-long variable names

---

game/src/main/org/apollo/game/message/impl/ItemOnNpcMessage.java
game/src/main/org/apollo/game/release/r317/ItemOnNpcMessageDecoder.java
game/src/main/org/apollo/game/release/r317/Release317.java
game/src/main/org/apollo/game/release/r377/ItemOnNpcMessageDecoder.java
game/src/main/org/apollo/game/release/r377/Release377.java

Based on some of Lmctruck's work in #306, but has 377 support too.
The frame opcode being the same as 317 is *not* a typo, by pure coincidence they're the same in both revisions.

Add Item on Npc

---

game/src/main/org/apollo/game/message/impl/ReportAbuseMessage.java
game/src/main/org/apollo/game/release/r317/Release317.java
game/src/main/org/apollo/game/release/r317/ReportAbuseMessageDecoder.java
game/src/main/org/apollo/game/release/r377/Release377.java
game/src/main/org/apollo/game/release/r377/ReportAbuseMessageDecoder.java

Based on work from Lmctruck in #306.

Add Report Abuse Message

---

game/src/main/java/org/apollo/game/model/entity/Player.java
game/src/main/kotlin/org/apollo/game/plugin/kotlin/KotlinPluginScript.kt
game/src/main/kotlin/stub.kt
game/src/plugins/cmd/meta.toml
game/src/plugins/cmd/src/animate-cmd.plugin.kts
game/src/plugins/cmd/src/bank-cmd.plugin.kts
game/src/plugins/cmd/src/item-cmd.plugin.kts
game/src/plugins/cmd/src/lookup.plugin.kts
game/src/plugins/cmd/src/messaging-cmd.plugin.kts
game/src/plugins/cmd/src/punish-cmd.plugin.kts
game/src/plugins/cmd/src/skill-cmd.plugin.kts
game/src/plugins/cmd/src/spawn-cmd.plugin.kts
game/src/plugins/cmd/src/teleport-cmd.plugin.kts
game/src/plugins/stub/stub.kt
game/src/plugins/util/command/meta.toml
game/src/plugins/util/command/src/command.kt

Convert commands from Ruby to Kotlin with 1:1 functionality.
TODO:

Convert commands to Kotlin

---

data/plugins/skill/magic/magic.rb

fix magic.rb

---

build.gradle
buildSrc/build.gradle
buildSrc/src/main/kotlin/org/apollo/build/compile/KotlinScriptCompiler.kt
buildSrc/src/main/kotlin/org/apollo/build/tasks/KotlinScriptCompileTask.kt
game/src/plugins/entity/spawn/src/spawn.plugin.kts
properties.gradle

MessageCollector needs updated.  The API has changed.

Share kotlin version config between buildSrc and project

---

util/build.gradle

Add RSA key gen Gradle task

---

net/src/main/org/apollo/net/codec/login/LoginDecoder.java

Fixes #322
Not sure about the logging level here -- open to suggestions.
I was manually setting breakpoints to debug a 377 client that had the modulus and public key params mixed up. Less than ideal 😅

Add logging to LoginDecoder for session rejections

---

game/plugin/skills/woodcutting/build.gradle
game/plugin/skills/woodcutting/meta.toml
game/plugin/skills/woodcutting/src/axe.kt
game/plugin/skills/woodcutting/src/wood.kt
game/plugin/skills/woodcutting/src/woodcutting.plugin.kts

OK, this is the new pr for wood cutting. The old branch imploded on a rebase. 
I need to migrate this to use async actions before it is ready to be merged.

Added woodcutting plugin for Kotlin

---

game/plugin/skills/fishing/build.gradle
game/plugin/skills/fishing/src/fishing.kt
game/plugin/skills/fishing/src/fishing.plugin.kts
game/plugin/skills/fishing/src/spots.kts

Hello,
This is a ported version of the fishing plugin in kotlin. 
I have also fixed the random chance of getting the lower level fish to be 70/30 instead of 50/50. 
I do not have a working test environment, I think t is correct, but I would greatly appreciate if someone could test this.  
This is only my second time working in Kotlin, so I would love some feedback!
I hope this helps!
~Trevor
- Identifying the positions fishing spots can move to (requires members OSRS but otherwise super easy), and adding a task to move them about (easy/medium).
- Evil bob random event
- Seaweed/casket stuff
- Identify algorithm used to determine whether or not a fish was caught

Added fishing plugin for Kotlin

---

game/plugin/api/src/org/apollo/game/plugins/api/position.kt
game/plugin/areas/build.gradle
game/plugin/areas/src/action.kt
game/plugin/areas/src/area.kt
game/plugin/areas/src/areas.plugin.kts
game/src/main/kotlin/org/apollo/game/plugin/kotlin/KotlinPluginScript.kt
game/src/main/kotlin/stub.kt

This PR also:
- Adds `Position` destructuring overloads in api
- Adds `on_event` to plugins

Port the area actions plugin
