apollo-rsps/apollo

game/src/main/org/apollo/game/message/handler/ItemOnObjectVerificationHandler.java, game/src/main/org/apollo/game/message/handler/ObjectActionVerificationHandler.java, game/src/test/org/apollo/game/message/handler/ChatMessageHandlerTest.java, game/src/test/org/apollo/game/message/handler/ItemOnItemVerificationHandlerTest.java, game/src/test/org/apollo/game/message/handler/ItemOnObjectVerificationHandlerTest.java, game/src/test/org/apollo/game/message/handler/ObjectActionVerificationHandlerTest.java, pom.xml
This introduces a couple of tests which verify that several of the MessageHandler implementations (Chat, ItemOnItem, ObjectAction) terminate messages appropriately. These few examples outline how tests like this could be written.
One issue I did find was that there is no verification that an object exists (as far as I can tell) in an ItemOnObject message. I'll write a few more tests and update any failing code as needed.
Admittedly mocking isn't necessarily needed here because we aren't accessing the file system or any system resources, but setting up all of these classes with all of their dependencies would be mayhem. 
* Mockito - A library for mocking classes in tests
* PowerMock - A mocking library to work around final classes and static methods
=> Add simple tests around 'important' Message verification handlers

.editorconfig, .gitignore
Quite a simple addition, which is compatible with most editors (IDEA, Vim, Eclipse, NetBeans, Sublime, Notepad++, so on...). This shouldn't be an issue for most editors since they will adapt the the current source code but people will always have their own settings.
The [EditorConfig](http://editorconfig.org/) provided will override the IDE defaults for indentation in Java and Ruby source code. It overrides the defaults for indentation and trailing whitespace, by making sure no trailing whitespace is kept (or at least highlighting it) and setting the indent size for Java to tabs with a width of 4, and spaces with a width of 2 for Ruby.
Additionally it makes sure no final newline is kept (had a look, this seems to be the norm across Apollo).
=> Add .editorconfig file to override IDE defaults

game/src/main/org/apollo/game/fs/decoder/SynchronousDecoder.java, game/src/main/org/apollo/game/fs/decoder/SynchronousDecoderException.java
Check for errors thrown during execution of any SynchronousDecoder tasks, and
rethrow any ExecutionExceptions as SynchronousDecoderExceptions.
Adds to the `executor` calls by using the Futures returned from the result of executor::submit and calling get() on them to cause any exceptions thrown to bubble up as ExecutionExceptions (see: [Future#get](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html#get--), in particular `ExecutionException - if the computation threw an exception`).
Currently, neither of the calls to `executor.shutdown()` or `executor.awaitTermination(...)` will cause an exception thrown by one of the tasks to be rethrown and will allow the server to continue cleanly as if no error occurred.
=> Handle errors thrown by SynchronousDecoder tasks

cache/src/main/org/apollo/cache/decoder/ItemDefinitionDecoder.java
* Replaces an OR, with what should have been an AND while decoding
unused item definition info.
=> Fix short circuit logic in ItemDefinitionDecoder

game/src/main/org/apollo/game/model/entity/WalkingQueue.java
Makes sure that the steps in a path sent for a "Player Walk" message are
on the same height level as the player that sent them beforethey are
added to the walking queue.
Fixes #109.
This is a bit of a crude fix, I think. Could this be better done in whatever handles steps in the WalkingQueue? cc @Major-
=> Correct the height levels of steps in a path

game/src/main/org/apollo/game/message/handler/EquipItemHandler.java
Fixes a peculiar bug related to equipping 2h swords. To reproduce,
start an action, and while doing that action equip a 2h sword. It
won't stop the action. The expected result is to stop the action
and require a restart.
Reproduce: http://webm.host/f0cbc/vid.webm
=> Fix actions continuing when equipping 2h swords

net/src/test/org/apollo/net/codec/game/TestGamePacketEncoder.java
Fixes the GamePacketEncoder unit test, there were errors migrating from the MTM encoder to the MTB encoder.
=> GamePacketEncoder unit test fix for MTM -> MTB encoder.

net/src/main/org/apollo/net/update/HttpRequestWorker.java
The spelling has been rectified as specified in the issue description.
=> Fixes #204 - corrected spelling of octet

util/src/test/org/apollo/util/NameUtilTests.java
Hello, 
I add a new case in the method test for encodedBases37.
I see the case for a character between 'A' and  'Z' was not tested so i did it.
=> added test case in methods encodedBases37 

data/plugins/skill/magic/alchemy.rb, data/plugins/skill/magic/convert.rb, data/plugins/skill/magic/enchant.rb, data/plugins/skill/magic/magic.rb, data/plugins/skill/magic/teleport.rb
* Fix OverRide Magic Spells
* Fix Process Element check
* Reordered the rune amounts so now it can be read clearly of how runescape has it by (primary, elemental)
* Changed MAGIC_SKILL_ID for add exp to Skill::Magic in enchant so you now gain exp instead of an error message
* For spells like alching they should always bring you back to your spell book even if you do not have the level requirment or the runes.
=> Fix Several Magic Issues

game/src/main/org/apollo/game/model/entity/Player.java
This being set to 1 resulted in nearby Players and NPCs taking a while to appear, because it would just be incremented once per tick.
=> Set default viewing distance to 15

util/src/main/org/apollo/util/LanguageUtil.java
Hello,
I found a redundant if in the method getIndefiniteArticle in the class LanguageUtil, so i remove it.
But something seems weird in the second if, the one i remove. Why is there just one '|' between first == 'l' and first == 'm' ?
Thanks.
=> Simplify the method getIndefiniteArticle

game/src/main/org/apollo/game/message/impl/SendProjectileMessage.java, game/src/main/org/apollo/game/model/area/Region.java, game/src/main/org/apollo/game/model/area/update/ProjectileUpdateOperation.java, game/src/main/org/apollo/game/model/entity/EntityType.java, game/src/main/org/apollo/game/model/entity/Mob.java, game/src/main/org/apollo/game/model/entity/Projectile.java, game/src/main/org/apollo/game/release/r377/Release377.java, game/src/main/org/apollo/game/release/r377/SendProjectileMessageEncoder.java
* Adds support for short-lived entities, which are never added to the
entity sets of the region they belong in.
* Adds support for checking the number of tiles a Mob occupies.
* Adds a ProjectileBuilder class to simplify creating projectiles.
=> Add support for projectiles

net/src/main/org/apollo/net/codec/game/GamePacketBuilder.java
Hello,
I thinked it will be better to put above the `tmp` variable. It clarify the function putBits and make it less redundant.
Thanks.
=> improve putBits

net/src/main/org/apollo/net/codec/game/GamePacketEncoder.java
Hello, 
I saw two useless if in `GamePacketEncoder` in the package `org.apollo.net.codec.game`.
I decided to remove these two if to make the method *encode* more simpler.
I also pass a line (line 34) to make it more readable.
Thanks.
=> Remove useless if

data/plugins/location/tutorial-island/instructions.rb
Hi, we saw two TODO in instructions.rb related to the update of the island progress, they say that it has to be set on moving around but in game it actually does it. Is it an oversight or maybe I misunderstood something ?
=> remove old TODO 

game/src/main/org/apollo/game/model/area/update/ItemUpdateOperation.java
Rearrange the arguments passed to the SendTileItemUpdateMessage
constructor when recording a ground item RegionUpdate.  Fixes #316.
=> Fix argument order of tile item message ctor call

build.gradle
Required or Apollo reaches the limit on boot. See #328.
=> Increase maximum heap size

.editorconfig
Uses the [recommended conventions](https://kotlinlang.org/docs/reference/coding-conventions.html#naming-style).
=> Add kotlin to .editorconfig

game/plugin/locations/varrock/build.gradle, game/plugin/locations/varrock/src/shops.plugin.kts, game/plugin/shops/build.gradle, game/plugin/shops/src/action.kt, game/plugin/shops/src/dls.kt, game/plugin/shops/src/shop.kt, game/plugin/shops/src/shop.plugin.kts, game/plugin/util/lookup/src/lookup.kt, game/src/main/java/org/apollo/game/message/handler/ItemVerificationHandler.java
Based on some great work from @tlf30 in #348, who ported the ruby plugin and the varrock shops. Changes since that include:
- Clean up the main shop code (which is from the crap ruby plugin that I wrote)
- Add a kotlin DSL
- Fix some bugs pointed out by Scu11 🤓
This also adds support for using the `lookup_{item, npc, object}` utility functions with an id appended to the string (which existed in the ruby version). Although this is utilised only as an internal implementation detail, we probably want to support this behaviour anyway.
Example of the old ruby DSL:
```ruby
create_shop npcs: :aubury, name: "Aubury's Rune Shop.", items: [
[:fire_rune, 5_000], [:water_rune, 5_000], [:air_rune, 5_000], [:earth_rune, 5_000],
[:mind_rune, 5_000], [:body_rune, 5_000], [:chaos_rune, 250], [:death_rune, …
```
=> Add shops in kotlin
